Add Codecov Report Generation
ballerina-platform/module-ballerina-java.arrays pull request #60
Opened 2021-03-01 11:55 UTC by gayaldassanayake

## Purpose
- Introducing `Codecov` code coverage report publishing to the `java.arrays` repository

## Goals
- Publishing the testerina generated code coverage xml to `Codecov` triggered via GitHub action of PR.

## Approach
- A new job is inserted to `Pull request` GitHub actions that publishes the XML report to  `Codecov`.
- These jobs trigger on merge to master or pull request and `CodeCov` generates a descriptive code coverage report.
- `Codecov` also adds comments to any PR made based on the code coverage changes between commits

## Test environment
- Ubuntu 20.04

2021-03-01 13:13 UTC, ThisaruGuruge approved these changes

2021-03-01 15:34 UTC, ThisaruGuruge requested changes
The coverage report is not publishing for PR.

2021-03-01 19:24 UTC, Kishanthan approved these changes

2021-03-02 03:33 UTC, ThisaruGuruge approved these changes

2021-03-02 03:33 UTC, merged